### ISSUE TITLE
Please remove .idea.

### ISSUE THREAD

**Issue by zhtnk** [tavor118/pythonjunior#1]
Please remove `.idea` folder from the repo, this should not be there.

**Comment by tavor118** [comment]
https://stackoverflow.com/questions/11124053/accidentally-committed-idea-directory-files-into-git

https://stackoverflow.com/questions/1143796/remove-a-file-from-a-git-repository-without-deleting-it-from-the-local-filesyste

**Comment by tavor118** [comment]
$ echo '.idea' >> .gitignore
$ git rm -r --cached .idea
$ git add .gitignore
$ git commit -m '(some message stating you added .idea to ignored entries)'
$ git push

**Comment by zhtnk** [comment]
Done!
